name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm test
        env:
          NEXT_PUBLIC_WEBAPP_URL: http://localhost:3000

      - name: Build project
        run: npm run build
        env:
          NEXT_PUBLIC_WEBAPP_URL: http://localhost:3000

  # This job will only run on pull requests and ensures all checks pass
  check-pr:
    if: github.event_name == 'pull_request'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: All checks passed
        run: echo "All CI checks have passed successfully!"
